# Generated by Django 4.0 on 2022-03-01 20:10

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_days_course_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=builtins.format)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=builtins.format)),
                ('time', models.CharField(max_length=50)),
                ('attendance', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.request')),
            ],
        ),
    ]
