# Generated by Django 4.0 on 2022-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_date_remove_request_attendance_remove_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateField(),
        ),
    ]
