# Generated by Django 4.0 on 2022-03-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_class_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
