# Generated by Django 4.0 on 2022-01-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.BigIntegerField(default=0)),
                ('credit', models.BigIntegerField(default=0)),
                ('classAmount', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('credit', models.BigIntegerField(default=0)),
                ('classAmount', models.BigIntegerField(default=0)),
                ('sdate', models.DateTimeField(blank=True, null=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('subscribed', models.BooleanField(blank=True, default=False, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='allowClass',
            field=models.ManyToManyField(to='subscription.Type'),
        ),
    ]
